services:
  - type: web
    name: ai-tax-advisor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # You'll need to set this in Render dashboard
      - key: GEMINI_MODEL
        value: gemini-2.0-flash-exp
      - key: GEMINI_MAX_TOKENS
        value: "8192"
      - key: GEMINI_TEMPERATURE
        value: "0.7"
      - key: GEMINI_REQUESTS_PER_MINUTE
        value: "15"
      - key: GEMINI_REQUESTS_PER_HOUR
        value: "900"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: logs
      mountPath: /opt/render/project/src/logs
      sizeGB: 1 